// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIXpQJ0Yti79h6evjG8fqwNQ6Ni87jBH4',
    appId: '1:371573411165:web:3f063d61f32335498f2cb4',
    messagingSenderId: '371573411165',
    projectId: 'notifyapp-8354f',
    authDomain: 'notifyapp-8354f.firebaseapp.com',
    storageBucket: 'notifyapp-8354f.firebasestorage.app',
    measurementId: 'G-82L5TH4TE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3e54QAbF3OsvEFZODtZ1hYMbxkdEjBVY',
    appId: '1:371573411165:android:1d9c0ad76d2d7e9f8f2cb4',
    messagingSenderId: '371573411165',
    projectId: 'notifyapp-8354f',
    storageBucket: 'notifyapp-8354f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7G-ctzyB88ab7_TsUzufipac3KruqH3I',
    appId: '1:371573411165:ios:880ea0a7cc2a176d8f2cb4',
    messagingSenderId: '371573411165',
    projectId: 'notifyapp-8354f',
    storageBucket: 'notifyapp-8354f.firebasestorage.app',
    iosBundleId: 'com.example.notifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7G-ctzyB88ab7_TsUzufipac3KruqH3I',
    appId: '1:371573411165:ios:880ea0a7cc2a176d8f2cb4',
    messagingSenderId: '371573411165',
    projectId: 'notifyapp-8354f',
    storageBucket: 'notifyapp-8354f.firebasestorage.app',
    iosBundleId: 'com.example.notifyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIXpQJ0Yti79h6evjG8fqwNQ6Ni87jBH4',
    appId: '1:371573411165:web:f0fee55fce691bca8f2cb4',
    messagingSenderId: '371573411165',
    projectId: 'notifyapp-8354f',
    authDomain: 'notifyapp-8354f.firebaseapp.com',
    storageBucket: 'notifyapp-8354f.firebasestorage.app',
    measurementId: 'G-3RCFHR0ZD1',
  );
}
